# Generated by Django 3.2 on 2021-04-21 17:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models.post


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title Of Your Post', max_length=50)),
                ('thumbnail', models.ImageField(upload_to='post_images/%Y/%m/%d/')),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('categories', models.CharField(choices=[('lifestyle', 'Lifestyle'), ('culture', 'Culture'), ('programming', 'Programming'), ('surveying', 'Surveying')], default='lifestyle', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to=main.models.post.get_image_filename, verbose_name='Image')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.post')),
            ],
            options={
                'db_table': 'notes',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('author', models.CharField(default='Guest', max_length=25)),
                ('comment', models.CharField(max_length=100)),
                ('added', models.DateField(default=datetime.datetime)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-added'],
            },
        ),
    ]
